✨ Add row wrapper component to enable external contexts like hook form
equinor/apollo-react-components pull request #30
Opened 2023-02-08 13:54 UTC by Simrayz

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change:

2023-02-08 14:24 UTC, mholta requested changes

2023-02-08 14:24 UTC, mholta commented on apps/playground/src/components/PokemonTable/PokemonTable.tsx
> +  console.log({ rowFromPokemon: row.original.name })
Remove?

2023-02-08 14:26 UTC, Simrayz commented on apps/playground/src/components/PokemonTable/PokemonTable.tsx
> +  console.log({ rowFromPokemon: row.original.name })
Fair, removed now

2023-02-08 18:49 UTC, cbuv requested changes
1. would be good to explain why this is needed, what use case it covers, and how this is supposed to be used. 

2. won't this break the HTML where a tr is a child of something other than tbody?

3. did you consider the react hook form issue with virtualized content? 
https://react-hook-form.com/advanced-usage#Workingwithvirtualizedlists 

Suggest we'll wait with expanding the component API until this feature is complete.

2023-02-09 07:39 UTC, Simrayz commented
> 1. would be good to explain why this is needed, what use case it covers, and how this is supposed to be used.
> 
>     2. won't this break the HTML where a tr is a child of something other than tbody?
> 
>     3. did you consider the react hook form issue with virtualized content?
>        https://react-hook-form.com/advanced-usage#Workingwithvirtualizedlists
> 
> 
> Suggest we'll wait with expanding the component API until this feature is complete.

I considered overwriting the `TableRow` component itself, but decided on a "Wrapper" instead. However, my intention is for this to be used for something like a `<Provider />` or a Fragment. So purely for state management/wrapping the table cells in some way.

2023-02-09 07:52 UTC, cbuv commented
> > 1. would be good to explain why this is needed, what use case it covers, and how this is supposed to be used.
> >    
> >    2. won't this break the HTML where a tr is a child of something other than tbody?
> >    3. did you consider the react hook form issue with virtualized content?
> >       https://react-hook-form.com/advanced-usage#Workingwithvirtualizedlists
> > 
> > Suggest we'll wait with expanding the component API until this feature is complete.
> 
> I considered overwriting the `TableRow` component itself, but decided on a "Wrapper" instead. However, my intention is for this to be used for something like a `<Provider />` or a Fragment. So purely for state management/wrapping the table cells in some way. @cbuv We could mark the config option as Preview/Unstable?

Yes, good idea! Marking the rowWrapper config option as unstable should let us proceed with this change.

2023-02-10 08:20 UTC, cbuv approved these changes

2023-02-10 09:03 UTC, merged