:hammer Storybook gh pages
equinor/apollo-react-components pull request #41
Opened 2023-02-21 11:20 UTC by cbuv

## What does this pull request change?
publish apollo-components storybook to github pages
Storybook available at https://equinor.github.io/apollo-react-components/

## Why is this pull request needed?
quickly explore this library

2023-02-24 07:11 UTC, mholta requested changes
Looks good!

2023-02-24 07:11 UTC, mholta commented on .github/workflows/storybook.yml
> +#      - main
Comment out

2023-02-24 07:11 UTC, mholta commented on .github/workflows/storybook.yml
> +      - name: Install and Build ⬇️ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this ste
Remove comment?

2023-02-24 09:17 UTC, mholta commented
Also, please add changeset

2023-03-01 19:23 UTC, cbuv commented on .github/workflows/storybook.yml
> +      - name: Install and Build ⬇️ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this ste
agree, removed in [380cf19](https://github.com/equinor/apollo-react-components/pull/41/commits/380cf199659a8d40b26b02ed2a683153cf70f21e)

2023-03-01 19:24 UTC, cbuv commented on .github/workflows/storybook.yml
> +#      - main
reverted in [380cf19](https://github.com/equinor/apollo-react-components/pull/41/commits/380cf199659a8d40b26b02ed2a683153cf70f21e)

2023-03-01 19:27 UTC, cbuv commented
> Also, please add changeset

I don't see any reasons to add a changeset for this change, since there are no changes to any package.

2023-03-03 08:18 UTC, mholta approved these changes
LGTM

2023-03-03 08:32 UTC, merged