feat/328226 add overflow cell
equinor/apollo-react-components pull request #47
Opened 2023-02-24 12:21 UTC by mholta

- ✨ add more complex mock data and another form example
- ✨ add show truncated content on hover
 
Should be discussed. Should this be a non configurable default.

## What does this pull request change?

- Add meta prop to show truncated content on hover
- Improve TypographyCustom by inheriting cell color from cell. This makes the component agnostic 
of color.

## Why is this pull request needed?

- To improve table when using fixed width

## Issues related to this change:
AB#328226

2023-02-24 14:12 UTC, cbuv commented
> Should be discussed. Should this be a non configurable default?

I think an opinionated default column is fine if it can be overridden (prop to useDataTable), for now, we should probably make it configurable.

2023-02-27 09:00 UTC, Simrayz approved these changes
LGTM. Leaving it as a configurable option for now is fine. I agree that it maybe should be the default - it depends how content other than text is rendered? 🤔

2023-02-27 09:09 UTC, mholta commented
Truncate or wrap

2023-02-27 11:12 UTC, Simrayz approved these changes
LGTM 🚀

2023-02-27 12:05 UTC, Simrayz requested changes
A lot of good work here, just one suggested change for clarity 😄

2023-02-27 12:05 UTC, Simrayz commented on packages/apollo-components/src/DataTable/useDataTable.tsx
> +        if (typeof truncateMode === 'function') truncateMode = truncateMode(cell)
Hmm, I would have written it like this:
```suggestion
      cell: ({ cell }) => {
        if (!cellConfig?.truncateMode) return 'hover'
        const truncateMode = typeof cell.truncateMode === 'function' ? truncateMode(cell) : cell.truncateMode
```

2023-02-27 12:08 UTC, mholta commented on packages/apollo-components/src/DataTable/useDataTable.tsx
> +        if (typeof truncateMode === 'function') truncateMode = truncateMode(cell)
Yes 👀

2023-02-27 12:36 UTC, Simrayz approved these changes
Let's go 🚀 🌠

2023-02-27 12:37 UTC, merged