✨  Add edit cells
equinor/apollo-react-components pull request #83
Opened 2023-03-31 12:56 UTC by mholta

- :bug: Specify dependency version number
- :package: Add new peer deps
- version packages
- version2
- move to components again
- ✨ Add react-hook-form edit cells and implement in example

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change:
[AB#348856](https://dev.azure.com/Equinor/5f972ff3-ed9a-4405-9db1-84542b5007a8/_workitems/edit/348856)

2023-04-19 09:15 UTC, mholta reviewed
Peer review with Constanza

2023-04-19 09:15 UTC, mholta commented on apps/jotai-form-example/src/features/unit-events-page/components/ActionsCell.tsx
> +        await mutatePokemon([newValues])
Mutate unit event

2023-04-19 09:20 UTC, consthauge requested changes

2023-04-19 09:20 UTC, consthauge commented on packages/apollo-components/src/form-cells/EditableTextFieldCell.tsx
> +import { TypographyCustom } from '../cells'
We should have a discussion about accessibility

2023-04-19 13:25 UTC, mholta commented on packages/apollo-components/src/form-cells/EditableTextFieldCell.tsx
> +import { TypographyCustom } from '../cells'
Yes, but this PR should probably be merged before that discussion, as we have multiple projects depending on it

2023-04-20 11:13 UTC, consthauge approved these changes

2023-04-20 11:13 UTC, consthauge commented on packages/apollo-components/src/cells/PopoverCell.tsx
> +export function PopoverCell(props: PopoverCellProps) {
Har dere bestemt dere for å gå for denne type syntaks nå?

2023-04-21 06:50 UTC, mholta commented on packages/apollo-components/src/cells/PopoverCell.tsx
> +export function PopoverCell(props: PopoverCellProps) {
Yes :)

2023-04-21 06:50 UTC, merged